name: VNC Screenshot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'graalvm'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew nativeCompile --no-configuration-cache

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y x11vnc xterm imagemagick xvfb fluxbox

    - name: Run VNC and take screenshot
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 &
        fluxbox &
        x11vnc -display :99 -nopw -listen localhost -xkb &
        xterm -display :99 -e "slmatrix/build/native/nativeCompile/slmatrix" &
        sleep 10
        import -window root -display :99 screenshot.png

    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: screenshot.png
